version: '3'

services:

  mysql-dev:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stocks
    ports:
      - "8000:3306"
    volumes:
      - ./sql_setup:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  myadmin-app:
    image: danieldinca11/adminapp_py
    volumes:
      - ./app_img/src:/app
    depends_on:
      - mysql-dev
    ports:
      - "8001:5000"

  myserver:
    image: danieldinca11/server_py
    volumes:
      - ./server_img/src:/app
    depends_on:
      - mysql-dev
    ports:
      - "8002:5000"

  myclient:
    image: danieldinca11/client_py
    volumes:
      - ./client_img/src:/app
    depends_on:
      - myadmin-app
      - myserver
    stdin_open: true

  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_DATA_MAX_SERIES_PER_DATABASE=0

  adapter:
    image: danieldinca11/adapter_py
    volumes:
      - ./adapter/src:/app
    depends_on:
      - mysql-dev
      - influxdb

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=stock_user
      - GF_SECURITY_ADMIN_PASSWORD=idp2019
    ports:
      - "80:3000"
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  mysql_data: {}
